<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class RetailProductSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $products = [
            // ── Herbicides (25) ──────────────────────────────────────────────
            ['name' => 'Glyphosate 360 SL 1L',         'category' => 'Herbicides',    'description' => 'Systemic non-selective herbicide for broad-spectrum weed control.',          'cost_price' => 28.00,  'sell_price' => 38.00,  'quantity' => 120, 'base_unit' => 'bottle',  'low_stock_alert' => 20],
            ['name' => 'Glyphosate 360 SL 5L',         'category' => 'Herbicides',    'description' => 'Systemic non-selective herbicide, 5-litre canister.',                         'cost_price' => 130.00, 'sell_price' => 175.00, 'quantity' => 60,  'base_unit' => 'canister','low_stock_alert' => 10],
            ['name' => 'Paraquat 200 SL 1L',           'category' => 'Herbicides',    'description' => 'Fast-acting contact herbicide for annual weeds.',                             'cost_price' => 32.00,  'sell_price' => 44.00,  'quantity' => 90,  'base_unit' => 'bottle',  'low_stock_alert' => 15],
            ['name' => 'Atrazine 500 SC 1L',           'category' => 'Herbicides',    'description' => 'Selective pre-emergent herbicide for maize.',                                 'cost_price' => 24.00,  'sell_price' => 33.00,  'quantity' => 80,  'base_unit' => 'bottle',  'low_stock_alert' => 15],
            ['name' => 'Pendimethalin 330 EC 1L',      'category' => 'Herbicides',    'description' => 'Pre-emergent herbicide for vegetables and cereals.',                          'cost_price' => 35.00,  'sell_price' => 48.00,  'quantity' => 70,  'base_unit' => 'bottle',  'low_stock_alert' => 10],
            ['name' => 'Butachlor 50 EC 1L',           'category' => 'Herbicides',    'description' => 'Selective pre-emergent herbicide for rice paddies.',                          'cost_price' => 30.00,  'sell_price' => 41.00,  'quantity' => 55,  'base_unit' => 'bottle',  'low_stock_alert' => 10],
            ['name' => '2,4-D Amine 720 SL 1L',       'category' => 'Herbicides',    'description' => 'Selective post-emergent herbicide for broadleaf weeds.',                      'cost_price' => 22.00,  'sell_price' => 30.00,  'quantity' => 100, 'base_unit' => 'bottle',  'low_stock_alert' => 20],
            ['name' => 'Metolachlor 960 EC 1L',        'category' => 'Herbicides',    'description' => 'Pre-emergent herbicide for grass in soybeans and maize.',                     'cost_price' => 38.00,  'sell_price' => 52.00,  'quantity' => 45,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Oxyfluorfen 240 EC 1L',        'category' => 'Herbicides',    'description' => 'Pre-emergent herbicide for alliums and brassicas.',                           'cost_price' => 40.00,  'sell_price' => 55.00,  'quantity' => 40,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Propanil 360 EC 1L',           'category' => 'Herbicides',    'description' => 'Post-emergent herbicide specifically for rice.',                              'cost_price' => 27.00,  'sell_price' => 37.00,  'quantity' => 65,  'base_unit' => 'bottle',  'low_stock_alert' => 10],
            ['name' => 'Halosulfuron 75 WG 100g',      'category' => 'Herbicides',    'description' => 'Post-emergent selective for nutsedge control.',                               'cost_price' => 45.00,  'sell_price' => 62.00,  'quantity' => 35,  'base_unit' => 'sachet',  'low_stock_alert' => 5],
            ['name' => 'Fluazifop-p-butyl 150 EC 1L',  'category' => 'Herbicides',    'description' => 'Post-emergent grass herbicide for broadleaf crops.',                          'cost_price' => 52.00,  'sell_price' => 70.00,  'quantity' => 30,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Imazapic 240 SL 1L',           'category' => 'Herbicides',    'description' => 'Selective herbicide for sugar cane and pastures.',                            'cost_price' => 60.00,  'sell_price' => 82.00,  'quantity' => 25,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Dicamba 480 SL 1L',            'category' => 'Herbicides',    'description' => 'Broadleaf weed control in cereals.',                                          'cost_price' => 33.00,  'sell_price' => 45.00,  'quantity' => 50,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Clethodim 240 EC 1L',          'category' => 'Herbicides',    'description' => 'Post-emergent grass herbicide in broadleaf crops.',                           'cost_price' => 48.00,  'sell_price' => 65.00,  'quantity' => 40,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Sethoxydim 187 EC 1L',         'category' => 'Herbicides',    'description' => 'Selective post-emergent grass herbicide.',                                    'cost_price' => 44.00,  'sell_price' => 60.00,  'quantity' => 35,  'base_unit' => 'bottle',  'low_stock_alert' => 6],
            ['name' => 'Quizalofop-p-ethyl 50 EC 1L',  'category' => 'Herbicides',    'description' => 'Grass herbicide for soybeans and cotton.',                                    'cost_price' => 55.00,  'sell_price' => 75.00,  'quantity' => 28,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Haloxyfop-P 108 EC 1L',        'category' => 'Herbicides',    'description' => 'Systemic grass herbicide with long residual activity.',                       'cost_price' => 58.00,  'sell_price' => 78.00,  'quantity' => 22,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Diuron 80 WP 1kg',             'category' => 'Herbicides',    'description' => 'Residual herbicide for sugarcane and non-crop areas.',                        'cost_price' => 36.00,  'sell_price' => 49.00,  'quantity' => 45,  'base_unit' => 'kg',      'low_stock_alert' => 8],
            ['name' => 'Terbutryn 500 SC 1L',          'category' => 'Herbicides',    'description' => 'Pre-emergent herbicide for cereals.',                                         'cost_price' => 29.00,  'sell_price' => 40.00,  'quantity' => 50,  'base_unit' => 'bottle',  'low_stock_alert' => 10],
            ['name' => 'Ametryn 500 SC 1L',            'category' => 'Herbicides',    'description' => 'Selective herbicide for sugarcane and pineapple.',                            'cost_price' => 31.00,  'sell_price' => 42.00,  'quantity' => 48,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Linuron 450 SC 1L',            'category' => 'Herbicides',    'description' => 'Residual herbicide for root vegetables and cereals.',                         'cost_price' => 34.00,  'sell_price' => 46.00,  'quantity' => 38,  'base_unit' => 'bottle',  'low_stock_alert' => 6],
            ['name' => 'Trifluralin 480 EC 1L',        'category' => 'Herbicides',    'description' => 'Pre-plant incorporated herbicide for vegetables.',                            'cost_price' => 26.00,  'sell_price' => 36.00,  'quantity' => 55,  'base_unit' => 'bottle',  'low_stock_alert' => 10],
            ['name' => 'Metribuzin 70 WP 1kg',         'category' => 'Herbicides',    'description' => 'Pre and post-emergent herbicide for potatoes and soybean.',                   'cost_price' => 42.00,  'sell_price' => 57.00,  'quantity' => 32,  'base_unit' => 'kg',      'low_stock_alert' => 5],
            ['name' => 'Benfluralin 1.5 G 10kg',       'category' => 'Herbicides',    'description' => 'Granular pre-emergent herbicide for tobacco and ornamentals.',                'cost_price' => 50.00,  'sell_price' => 68.00,  'quantity' => 20,  'base_unit' => 'bag',     'low_stock_alert' => 4],

            // ── Fungicides (25) ──────────────────────────────────────────────
            ['name' => 'Mancozeb 80 WP 1kg',           'category' => 'Fungicides',    'description' => 'Broad-spectrum protective fungicide for many crops.',                         'cost_price' => 18.00,  'sell_price' => 26.00,  'quantity' => 150, 'base_unit' => 'kg',      'low_stock_alert' => 25],
            ['name' => 'Mancozeb 80 WP 500g',          'category' => 'Fungicides',    'description' => 'Broad-spectrum protective fungicide — 500g pack.',                           'cost_price' => 10.00,  'sell_price' => 15.00,  'quantity' => 200, 'base_unit' => 'pack',    'low_stock_alert' => 30],
            ['name' => 'Metalaxyl-M 350 ES 1L',        'category' => 'Fungicides',    'description' => 'Systemic fungicide for seed treatment against Pythium and Phytophthora.',     'cost_price' => 65.00,  'sell_price' => 88.00,  'quantity' => 30,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Propiconazole 250 EC 1L',      'category' => 'Fungicides',    'description' => 'Systemic triazole fungicide for cereals and turf.',                           'cost_price' => 55.00,  'sell_price' => 75.00,  'quantity' => 45,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Tebuconazole 250 EW 1L',       'category' => 'Fungicides',    'description' => 'Systemic fungicide for wheat and vegetable diseases.',                        'cost_price' => 58.00,  'sell_price' => 78.00,  'quantity' => 40,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Azoxystrobin 250 SC 1L',       'category' => 'Fungicides',    'description' => 'Broad-spectrum strobilurin fungicide.',                                       'cost_price' => 72.00,  'sell_price' => 97.00,  'quantity' => 35,  'base_unit' => 'bottle',  'low_stock_alert' => 6],
            ['name' => 'Thiram 75 WP 1kg',             'category' => 'Fungicides',    'description' => 'Protective fungicide and seed dressing.',                                     'cost_price' => 20.00,  'sell_price' => 28.00,  'quantity' => 80,  'base_unit' => 'kg',      'low_stock_alert' => 15],
            ['name' => 'Captan 50 WP 1kg',             'category' => 'Fungicides',    'description' => 'Contact fungicide for tubers and fruits.',                                    'cost_price' => 22.00,  'sell_price' => 30.00,  'quantity' => 75,  'base_unit' => 'kg',      'low_stock_alert' => 12],
            ['name' => 'Carbendazim 500 SC 1L',        'category' => 'Fungicides',    'description' => 'Broad-spectrum systemic benzimidazole fungicide.',                            'cost_price' => 35.00,  'sell_price' => 48.00,  'quantity' => 60,  'base_unit' => 'bottle',  'low_stock_alert' => 10],
            ['name' => 'Iprodione 500 SC 1L',          'category' => 'Fungicides',    'description' => 'Contact fungicide for Botrytis and Sclerotinia.',                             'cost_price' => 48.00,  'sell_price' => 65.00,  'quantity' => 40,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Chlorothalonil 720 SC 1L',     'category' => 'Fungicides',    'description' => 'Multipurpose contact fungicide.',                                             'cost_price' => 30.00,  'sell_price' => 41.00,  'quantity' => 70,  'base_unit' => 'bottle',  'low_stock_alert' => 12],
            ['name' => 'Cymoxanil 45 WP 500g',         'category' => 'Fungicides',    'description' => 'Systemic fungicide for late blight control.',                                 'cost_price' => 40.00,  'sell_price' => 55.00,  'quantity' => 50,  'base_unit' => 'pack',    'low_stock_alert' => 8],
            ['name' => 'Dimethomorph 50 WP 500g',      'category' => 'Fungicides',    'description' => 'Systemic oomycide for potato and grape downy mildew.',                        'cost_price' => 55.00,  'sell_price' => 74.00,  'quantity' => 35,  'base_unit' => 'pack',    'low_stock_alert' => 6],
            ['name' => 'Fosetyl-Al 80 WP 1kg',         'category' => 'Fungicides',    'description' => 'Systemic fungicide for Phytophthora and Plasmopara.',                        'cost_price' => 45.00,  'sell_price' => 62.00,  'quantity' => 40,  'base_unit' => 'kg',      'low_stock_alert' => 8],
            ['name' => 'Hexaconazole 50 SC 1L',        'category' => 'Fungicides',    'description' => 'Systemic triazole for paddy rice blast and sheath blight.',                   'cost_price' => 50.00,  'sell_price' => 68.00,  'quantity' => 42,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Difenoconazole 250 EC 1L',     'category' => 'Fungicides',    'description' => 'Broad-spectrum triazole fungicide.',                                          'cost_price' => 60.00,  'sell_price' => 82.00,  'quantity' => 30,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Epoxiconazole 125 SC 1L',      'category' => 'Fungicides',    'description' => 'Systemic triazole for cereal diseases.',                                      'cost_price' => 62.00,  'sell_price' => 84.00,  'quantity' => 28,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Fludioxonil 25 FS 1L',         'category' => 'Fungicides',    'description' => 'Phenylpyrrole seed treatment fungicide.',                                     'cost_price' => 70.00,  'sell_price' => 95.00,  'quantity' => 25,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'Kresoxim-methyl 500 SC 1L',    'category' => 'Fungicides',    'description' => 'Strobilurin fungicide for powdery mildew and scab.',                          'cost_price' => 68.00,  'sell_price' => 92.00,  'quantity' => 22,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'Myclobutanil 190 EW 1L',       'category' => 'Fungicides',    'description' => 'Systemic fungicide for powdery mildew in grapes.',                            'cost_price' => 65.00,  'sell_price' => 88.00,  'quantity' => 26,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'Trifloxystrobin 500 WG 200g',  'category' => 'Fungicides',    'description' => 'Broad-spectrum strobilurin for fruits and cereals.',                          'cost_price' => 75.00,  'sell_price' => 102.00, 'quantity' => 20,  'base_unit' => 'sachet',  'low_stock_alert' => 4],
            ['name' => 'Paclobutrazol 250 SC 1L',      'category' => 'Fungicides',    'description' => 'Triazole fungicide and plant growth regulator for mango.',                    'cost_price' => 80.00,  'sell_price' => 108.00, 'quantity' => 18,  'base_unit' => 'bottle',  'low_stock_alert' => 3],
            ['name' => 'Penconazole 100 EC 1L',        'category' => 'Fungicides',    'description' => 'Systemic triazole for powdery mildew in grapes and apples.',                  'cost_price' => 55.00,  'sell_price' => 75.00,  'quantity' => 30,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Triadimefon 250 WP 1kg',       'category' => 'Fungicides',    'description' => 'Systemic triazole for rusts and powdery mildew.',                             'cost_price' => 42.00,  'sell_price' => 57.00,  'quantity' => 35,  'base_unit' => 'kg',      'low_stock_alert' => 6],
            ['name' => 'Vinclozolin 500 SC 1L',        'category' => 'Fungicides',    'description' => 'Contact fungicide for grey mould and white rot.',                             'cost_price' => 46.00,  'sell_price' => 63.00,  'quantity' => 32,  'base_unit' => 'bottle',  'low_stock_alert' => 5],

            // ── Insecticides (30) ─────────────────────────────────────────────
            ['name' => 'Lambda-cyhalothrin 25 EC 1L',  'category' => 'Insecticides',  'description' => 'Broad-spectrum pyrethroid for vegetables and cereals.',                       'cost_price' => 32.00,  'sell_price' => 44.00,  'quantity' => 110, 'base_unit' => 'bottle',  'low_stock_alert' => 20],
            ['name' => 'Cypermethrin 200 EC 1L',       'category' => 'Insecticides',  'description' => 'Broad-spectrum pyrethroid insecticide.',                                      'cost_price' => 28.00,  'sell_price' => 38.00,  'quantity' => 130, 'base_unit' => 'bottle',  'low_stock_alert' => 20],
            ['name' => 'Chlorpyrifos 480 EC 1L',       'category' => 'Insecticides',  'description' => 'Organophosphate against soil and foliar insects.',                            'cost_price' => 25.00,  'sell_price' => 35.00,  'quantity' => 100, 'base_unit' => 'bottle',  'low_stock_alert' => 20],
            ['name' => 'Dimethoate 400 EC 1L',         'category' => 'Insecticides',  'description' => 'Systemic organophosphate for sucking pests.',                                 'cost_price' => 24.00,  'sell_price' => 33.00,  'quantity' => 95,  'base_unit' => 'bottle',  'low_stock_alert' => 15],
            ['name' => 'Imidacloprid 200 SL 1L',       'category' => 'Insecticides',  'description' => 'Systemic neonicotinoid for sucking insects.',                                 'cost_price' => 52.00,  'sell_price' => 70.00,  'quantity' => 75,  'base_unit' => 'bottle',  'low_stock_alert' => 12],
            ['name' => 'Acetamiprid 200 SP 100g',      'category' => 'Insecticides',  'description' => 'Neonicotinoid for whitefly, thrips and aphids.',                              'cost_price' => 38.00,  'sell_price' => 52.00,  'quantity' => 60,  'base_unit' => 'sachet',  'low_stock_alert' => 10],
            ['name' => 'Thiamethoxam 240 SC 1L',       'category' => 'Insecticides',  'description' => 'Systemic neonicotinoid for seed and foliar treatment.',                       'cost_price' => 58.00,  'sell_price' => 78.00,  'quantity' => 50,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Clothianidin 600 FS 1L',       'category' => 'Insecticides',  'description' => 'Neonicotinoid seed treatment against soil and early pests.',                  'cost_price' => 65.00,  'sell_price' => 88.00,  'quantity' => 35,  'base_unit' => 'bottle',  'low_stock_alert' => 6],
            ['name' => 'Fipronil 200 SC 1L',           'category' => 'Insecticides',  'description' => 'Phenylpyrazole insecticide for stem borers and termites.',                    'cost_price' => 55.00,  'sell_price' => 75.00,  'quantity' => 45,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Emamectin Benzoate 19 EC 1L',  'category' => 'Insecticides',  'description' => 'Avermectin insecticide for caterpillars and leafminers.',                     'cost_price' => 60.00,  'sell_price' => 82.00,  'quantity' => 40,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Spinosad 480 SC 1L',           'category' => 'Insecticides',  'description' => 'Biological insecticide for lepidopteran larvae.',                             'cost_price' => 72.00,  'sell_price' => 97.00,  'quantity' => 30,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Abamectin 18 EC 1L',           'category' => 'Insecticides',  'description' => 'Biological insecticide/miticide for spider mites and leafminers.',            'cost_price' => 68.00,  'sell_price' => 92.00,  'quantity' => 32,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Deltamethrin 25 EC 1L',        'category' => 'Insecticides',  'description' => 'Type II pyrethroid for stored products and field crops.',                     'cost_price' => 30.00,  'sell_price' => 41.00,  'quantity' => 85,  'base_unit' => 'bottle',  'low_stock_alert' => 15],
            ['name' => 'Bifenthrin 100 EC 1L',         'category' => 'Insecticides',  'description' => 'Broad-spectrum pyrethroid with good residual activity.',                      'cost_price' => 42.00,  'sell_price' => 57.00,  'quantity' => 55,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Permethrin 500 EC 1L',         'category' => 'Insecticides',  'description' => 'Pyrethroid for cotton, vegetables and stored grain.',                         'cost_price' => 35.00,  'sell_price' => 48.00,  'quantity' => 70,  'base_unit' => 'bottle',  'low_stock_alert' => 12],
            ['name' => 'Profenofos 500 EC 1L',         'category' => 'Insecticides',  'description' => 'Contact and systemic OP for cotton bollworm and mites.',                      'cost_price' => 38.00,  'sell_price' => 52.00,  'quantity' => 60,  'base_unit' => 'bottle',  'low_stock_alert' => 10],
            ['name' => 'Malathion 500 EC 1L',          'category' => 'Insecticides',  'description' => 'Non-systemic OP for broad insect control.',                                   'cost_price' => 20.00,  'sell_price' => 28.00,  'quantity' => 110, 'base_unit' => 'bottle',  'low_stock_alert' => 20],
            ['name' => 'Triazophos 400 EC 1L',         'category' => 'Insecticides',  'description' => 'Organophosphate against caterpillars and mites on rice.',                     'cost_price' => 33.00,  'sell_price' => 45.00,  'quantity' => 55,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Carbaryl 850 WP 1kg',          'category' => 'Insecticides',  'description' => 'Carbamate insecticide for chewing insects.',                                  'cost_price' => 26.00,  'sell_price' => 36.00,  'quantity' => 80,  'base_unit' => 'kg',      'low_stock_alert' => 12],
            ['name' => 'Methomyl 90 SP 500g',          'category' => 'Insecticides',  'description' => 'Systemic carbamate for caterpillars and flies.',                              'cost_price' => 44.00,  'sell_price' => 60.00,  'quantity' => 40,  'base_unit' => 'pack',    'low_stock_alert' => 6],
            ['name' => 'Phosmet 50 WP 1kg',            'category' => 'Insecticides',  'description' => 'Organophosphate for codling moth in fruits.',                                 'cost_price' => 48.00,  'sell_price' => 65.00,  'quantity' => 30,  'base_unit' => 'kg',      'low_stock_alert' => 5],
            ['name' => 'Indoxacarb 150 SC 1L',         'category' => 'Insecticides',  'description' => 'Oxadiazine insecticide for caterpillars in vegetables.',                      'cost_price' => 65.00,  'sell_price' => 88.00,  'quantity' => 28,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Chlorfenapyr 360 SC 1L',       'category' => 'Insecticides',  'description' => 'Pyrrole insecticide for diamondback moth and mites.',                         'cost_price' => 70.00,  'sell_price' => 95.00,  'quantity' => 25,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'Novaluron 100 EC 1L',          'category' => 'Insecticides',  'description' => 'IGR for whitefly and leafminer larvae.',                                      'cost_price' => 72.00,  'sell_price' => 97.00,  'quantity' => 22,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'Lufenuron 050 EC 1L',          'category' => 'Insecticides',  'description' => 'Insect growth regulator for caterpillars.',                                   'cost_price' => 68.00,  'sell_price' => 92.00,  'quantity' => 24,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'Teflubenzuron 150 SC 1L',      'category' => 'Insecticides',  'description' => 'Benzoylurea IGR for lepidopteran control.',                                   'cost_price' => 64.00,  'sell_price' => 87.00,  'quantity' => 20,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'Pyriproxyfen 100 EC 1L',       'category' => 'Insecticides',  'description' => 'JHA insect growth regulator for whitefly and scale.',                         'cost_price' => 60.00,  'sell_price' => 82.00,  'quantity' => 26,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'Spiromesifen 240 SC 1L',       'category' => 'Insecticides',  'description' => 'Lipid biosynthesis inhibitor for mites and whitefly.',                        'cost_price' => 75.00,  'sell_price' => 102.00, 'quantity' => 18,  'base_unit' => 'bottle',  'low_stock_alert' => 3],
            ['name' => 'Cyflumetofen 200 SC 1L',       'category' => 'Insecticides',  'description' => 'Novel complex II miticide for tetranychid mites.',                            'cost_price' => 82.00,  'sell_price' => 110.00, 'quantity' => 15,  'base_unit' => 'bottle',  'low_stock_alert' => 3],
            ['name' => 'Hexythiazox 100 EC 1L',        'category' => 'Insecticides',  'description' => 'Selective miticide for eggs and early stages of mites.',                      'cost_price' => 58.00,  'sell_price' => 78.00,  'quantity' => 28,  'base_unit' => 'bottle',  'low_stock_alert' => 5],

            // ── Fertilizers (25) ─────────────────────────────────────────────
            ['name' => 'NPK 15-15-15 50kg',            'category' => 'Fertilizers',   'description' => 'Balanced compound fertilizer for general crop use.',                          'cost_price' => 140.00, 'sell_price' => 185.00, 'quantity' => 200, 'base_unit' => 'bag',     'low_stock_alert' => 30],
            ['name' => 'NPK 20-10-10 50kg',            'category' => 'Fertilizers',   'description' => 'High-nitrogen compound fertilizer for leafy crops.',                          'cost_price' => 145.00, 'sell_price' => 192.00, 'quantity' => 160, 'base_unit' => 'bag',     'low_stock_alert' => 25],
            ['name' => 'Urea 46% N 50kg',              'category' => 'Fertilizers',   'description' => 'High-nitrogen fertilizer for topdressing.',                                   'cost_price' => 130.00, 'sell_price' => 172.00, 'quantity' => 180, 'base_unit' => 'bag',     'low_stock_alert' => 30],
            ['name' => 'CAN 26% N 50kg',               'category' => 'Fertilizers',   'description' => 'Calcium ammonium nitrate for topdressing cereals.',                           'cost_price' => 120.00, 'sell_price' => 158.00, 'quantity' => 140, 'base_unit' => 'bag',     'low_stock_alert' => 20],
            ['name' => 'DAP 18-46-0 50kg',             'category' => 'Fertilizers',   'description' => 'Di-ammonium phosphate for basal application.',                               'cost_price' => 155.00, 'sell_price' => 205.00, 'quantity' => 120, 'base_unit' => 'bag',     'low_stock_alert' => 20],
            ['name' => 'MOP 60% K2O 50kg',             'category' => 'Fertilizers',   'description' => 'Muriate of potash for potassium deficiency correction.',                      'cost_price' => 145.00, 'sell_price' => 192.00, 'quantity' => 100, 'base_unit' => 'bag',     'low_stock_alert' => 15],
            ['name' => 'Single Super Phosphate 50kg',   'category' => 'Fertilizers',   'description' => 'SSP for basal phosphate and sulphur supply.',                                 'cost_price' => 110.00, 'sell_price' => 145.00, 'quantity' => 90,  'base_unit' => 'bag',     'low_stock_alert' => 15],
            ['name' => 'Ammonium Sulphate 21% N 50kg', 'category' => 'Fertilizers',   'description' => 'Nitrogen and sulphur fertilizer, acidifying.',                                'cost_price' => 115.00, 'sell_price' => 152.00, 'quantity' => 80,  'base_unit' => 'bag',     'low_stock_alert' => 12],
            ['name' => 'Foliar Fertilizer Amino 500ml','category' => 'Fertilizers',   'description' => 'Amino acid-based foliar feed for vigour and fruit set.',                      'cost_price' => 22.00,  'sell_price' => 32.00,  'quantity' => 120, 'base_unit' => 'bottle',  'low_stock_alert' => 20],
            ['name' => 'Micronutrient Mix Foliar 1L',  'category' => 'Fertilizers',   'description' => 'Complete micronutrient foliar spray (Fe, Mn, Zn, B, Mo, Cu).',               'cost_price' => 38.00,  'sell_price' => 52.00,  'quantity' => 80,  'base_unit' => 'bottle',  'low_stock_alert' => 12],
            ['name' => 'Zinc Sulphate 21% 25kg',       'category' => 'Fertilizers',   'description' => 'Corrects zinc deficiency in soil and foliar application.',                    'cost_price' => 65.00,  'sell_price' => 87.00,  'quantity' => 60,  'base_unit' => 'bag',     'low_stock_alert' => 10],
            ['name' => 'Borax 11% B 25kg',             'category' => 'Fertilizers',   'description' => 'Boron source for fruit set and quality improvement.',                         'cost_price' => 55.00,  'sell_price' => 74.00,  'quantity' => 50,  'base_unit' => 'bag',     'low_stock_alert' => 8],
            ['name' => 'Calcium Nitrate 15.5% N 25kg', 'category' => 'Fertilizers',   'description' => 'Water-soluble calcium and nitrogen for fertigating.',                         'cost_price' => 85.00,  'sell_price' => 113.00, 'quantity' => 55,  'base_unit' => 'bag',     'low_stock_alert' => 8],
            ['name' => 'Potassium Nitrate 13-0-46 25kg','category' => 'Fertilizers',  'description' => 'Chloride-free NK fertilizer for fertigation.',                                'cost_price' => 110.00, 'sell_price' => 145.00, 'quantity' => 40,  'base_unit' => 'bag',     'low_stock_alert' => 6],
            ['name' => 'Magnesium Sulphate 25kg',      'category' => 'Fertilizers',   'description' => 'Kieserite for magnesium and sulphur deficiency.',                             'cost_price' => 58.00,  'sell_price' => 78.00,  'quantity' => 45,  'base_unit' => 'bag',     'low_stock_alert' => 6],
            ['name' => 'Humic Acid 70% 1kg',           'category' => 'Fertilizers',   'description' => 'Soil conditioner and biostimulant powder.',                                   'cost_price' => 35.00,  'sell_price' => 48.00,  'quantity' => 90,  'base_unit' => 'kg',      'low_stock_alert' => 15],
            ['name' => 'Seaweed Extract SL 1L',        'category' => 'Fertilizers',   'description' => 'Biostimulant for yield and stress resistance.',                               'cost_price' => 28.00,  'sell_price' => 39.00,  'quantity' => 100, 'base_unit' => 'bottle',  'low_stock_alert' => 15],
            ['name' => 'Potassium Humate 1L',          'category' => 'Fertilizers',   'description' => 'Liquid humate for soil structure and nutrient uptake.',                       'cost_price' => 25.00,  'sell_price' => 35.00,  'quantity' => 85,  'base_unit' => 'bottle',  'low_stock_alert' => 12],
            ['name' => 'NPK 12-12-17 + 2MgO 25kg',    'category' => 'Fertilizers',   'description' => 'Turf and vegetable granular fertilizer with Magnesium.',                       'cost_price' => 95.00,  'sell_price' => 127.00, 'quantity' => 50,  'base_unit' => 'bag',     'low_stock_alert' => 8],
            ['name' => 'Sulphate of Potash 50% 25kg',  'category' => 'Fertilizers',   'description' => 'Chloride-free potassium for sensitive crops.',                                'cost_price' => 120.00, 'sell_price' => 158.00, 'quantity' => 40,  'base_unit' => 'bag',     'low_stock_alert' => 6],
            ['name' => 'Ferrous Sulphate 20% Fe 25kg', 'category' => 'Fertilizers',   'description' => 'Corrects iron chlorosis in calcareous soils.',                               'cost_price' => 60.00,  'sell_price' => 81.00,  'quantity' => 35,  'base_unit' => 'bag',     'low_stock_alert' => 5],
            ['name' => 'Manganese Sulphate 32% 25kg',  'category' => 'Fertilizers',   'description' => 'Manganese source for soil and foliar application.',                           'cost_price' => 68.00,  'sell_price' => 91.00,  'quantity' => 30,  'base_unit' => 'bag',     'low_stock_alert' => 5],
            ['name' => 'Copper Sulphate 25% 25kg',     'category' => 'Fertilizers',   'description' => 'Copper deficiency correction and fungicidal properties.',                     'cost_price' => 72.00,  'sell_price' => 97.00,  'quantity' => 28,  'base_unit' => 'bag',     'low_stock_alert' => 4],
            ['name' => 'Silicon Fertilizer SL 1L',     'category' => 'Fertilizers',   'description' => 'Silicon for cell wall strengthening and disease resistance.',                  'cost_price' => 30.00,  'sell_price' => 41.00,  'quantity' => 70,  'base_unit' => 'bottle',  'low_stock_alert' => 10],
            ['name' => 'Organic Compost Granule 50kg', 'category' => 'Fertilizers',   'description' => 'Composted organic matter for soil health and base nutrients.',                 'cost_price' => 80.00,  'sell_price' => 106.00, 'quantity' => 80,  'base_unit' => 'bag',     'low_stock_alert' => 12],

            // ── Plant Growth Regulators (15) ──────────────────────────────────
            ['name' => 'Gibberellic Acid 20% SP 10g',  'category' => 'Growth Regulators','description' => 'Promotes stem elongation and fruit setting.',                              'cost_price' => 15.00,  'sell_price' => 21.00,  'quantity' => 150, 'base_unit' => 'sachet',  'low_stock_alert' => 25],
            ['name' => 'Cytokinin 40 SL 1L',           'category' => 'Growth Regulators','description' => 'Promotes cell division, branching and fruit retention.',                   'cost_price' => 32.00,  'sell_price' => 44.00,  'quantity' => 80,  'base_unit' => 'bottle',  'low_stock_alert' => 12],
            ['name' => 'Ethephon 480 SL 1L',           'category' => 'Growth Regulators','description' => 'Ethylene-releasing compound for uniform ripening.',                        'cost_price' => 35.00,  'sell_price' => 48.00,  'quantity' => 65,  'base_unit' => 'bottle',  'low_stock_alert' => 10],
            ['name' => 'Trinexapac-ethyl 250 SC 1L',   'category' => 'Growth Regulators','description' => 'Lodging prevention growth retardant for cereals.',                         'cost_price' => 55.00,  'sell_price' => 75.00,  'quantity' => 40,  'base_unit' => 'bottle',  'low_stock_alert' => 6],
            ['name' => 'Mepiquat Chloride 50 SL 1L',   'category' => 'Growth Regulators','description' => 'Plant growth regulator for cotton canopy management.',                     'cost_price' => 42.00,  'sell_price' => 57.00,  'quantity' => 35,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Prohexadione-Ca 10 WP 500g',   'category' => 'Growth Regulators','description' => 'Lodging prevention retardant in rice and wheat.',                          'cost_price' => 48.00,  'sell_price' => 65.00,  'quantity' => 30,  'base_unit' => 'pack',    'low_stock_alert' => 5],
            ['name' => 'Daminozide 850 WP 500g',       'category' => 'Growth Regulators','description' => 'Growth retardant for compact and uniform crops.',                          'cost_price' => 52.00,  'sell_price' => 70.00,  'quantity' => 25,  'base_unit' => 'pack',    'low_stock_alert' => 4],
            ['name' => 'Chlormequat Chloride 460 SL 1L','category' => 'Growth Regulators','description' => 'Stem shortener for cereals; improves harvest index.',                     'cost_price' => 38.00,  'sell_price' => 52.00,  'quantity' => 40,  'base_unit' => 'bottle',  'low_stock_alert' => 6],
            ['name' => '1-MCP Sachet 3.3% 5g',         'category' => 'Growth Regulators','description' => '1-methylcyclopropene for post-harvest ethylene blocking.',                 'cost_price' => 10.00,  'sell_price' => 15.00,  'quantity' => 200, 'base_unit' => 'sachet',  'low_stock_alert' => 30],
            ['name' => 'CPPU Cytokinin 10 SL 1L',      'category' => 'Growth Regulators','description' => 'Forchlorfenuron for fruit enlargement in kiwi and grape.',                 'cost_price' => 68.00,  'sell_price' => 92.00,  'quantity' => 22,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'IAA Root Enhancer 1L',         'category' => 'Growth Regulators','description' => 'Indole-acetic acid for rooting and transplant establishment.',              'cost_price' => 30.00,  'sell_price' => 41.00,  'quantity' => 70,  'base_unit' => 'bottle',  'low_stock_alert' => 10],
            ['name' => 'IBA Rooting Powder 3000ppm 50g','category' => 'Growth Regulators','description' => 'Indole-butyric acid for vegetative cuttings.',                            'cost_price' => 18.00,  'sell_price' => 25.00,  'quantity' => 100, 'base_unit' => 'pack',    'low_stock_alert' => 15],
            ['name' => 'NAA 4.5% SL 1L',              'category' => 'Growth Regulators','description' => 'Naphthaleneacetic acid for fruit thinning and rooting.',                   'cost_price' => 35.00,  'sell_price' => 48.00,  'quantity' => 50,  'base_unit' => 'bottle',  'low_stock_alert' => 8],
            ['name' => 'Brassinolide 0.01% SL 1L',    'category' => 'Growth Regulators','description' => 'Brassinosteroid for stress tolerance and yield increase.',                  'cost_price' => 58.00,  'sell_price' => 78.00,  'quantity' => 28,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Triacontanol 0.1% EW 1L',     'category' => 'Growth Regulators','description' => 'Natural growth promoter for improved photosynthesis.',                      'cost_price' => 28.00,  'sell_price' => 38.00,  'quantity' => 60,  'base_unit' => 'bottle',  'low_stock_alert' => 10],

            // ── Nematicides (10) ──────────────────────────────────────────────
            ['name' => 'Carbosulfan 200 CS 1L',        'category' => 'Nematicides',   'description' => 'Seed treatment nematicide and soil insecticide.',                             'cost_price' => 55.00,  'sell_price' => 75.00,  'quantity' => 40,  'base_unit' => 'bottle',  'low_stock_alert' => 6],
            ['name' => 'Terbufos 15 G 10kg',           'category' => 'Nematicides',   'description' => 'Soil granule nematicide for maize and soybean.',                             'cost_price' => 90.00,  'sell_price' => 122.00, 'quantity' => 30,  'base_unit' => 'bag',     'low_stock_alert' => 5],
            ['name' => 'Cadusafos 10 G 10kg',          'category' => 'Nematicides',   'description' => 'Organophosphate nematicide granules for vegetable nematodes.',               'cost_price' => 100.00, 'sell_price' => 135.00, 'quantity' => 25,  'base_unit' => 'bag',     'low_stock_alert' => 4],
            ['name' => 'Fosthiazate 150 SC 1L',        'category' => 'Nematicides',   'description' => 'Systemic nematicide for root-knot and cyst nematodes.',                      'cost_price' => 85.00,  'sell_price' => 115.00, 'quantity' => 28,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'Fluopyram 500 SC 1L',          'category' => 'Nematicides',   'description' => 'SDHI fungicide/nematicide for soil nematodes.',                              'cost_price' => 110.00, 'sell_price' => 148.00, 'quantity' => 20,  'base_unit' => 'bottle',  'low_stock_alert' => 3],
            ['name' => 'Oxamyl 24% SL 1L',             'category' => 'Nematicides',   'description' => 'Systemic carbamate nematicide/insecticide.',                                 'cost_price' => 72.00,  'sell_price' => 97.00,  'quantity' => 30,  'base_unit' => 'bottle',  'low_stock_alert' => 5],
            ['name' => 'Dazomet 98% GR 25kg',          'category' => 'Nematicides',   'description' => 'Soil fumigant for nematodes, fungi and weed seeds.',                         'cost_price' => 180.00, 'sell_price' => 240.00, 'quantity' => 15,  'base_unit' => 'bag',     'low_stock_alert' => 3],
            ['name' => 'Dimethyl Disulphide 1L',       'category' => 'Nematicides',   'description' => 'Biofumigant for pre-plant soil nematode control.',                           'cost_price' => 95.00,  'sell_price' => 128.00, 'quantity' => 18,  'base_unit' => 'bottle',  'low_stock_alert' => 3],
            ['name' => 'Purpureocillium lilacinum 1L', 'category' => 'Nematicides',   'description' => 'Biocontrol nematicide — fungal parasite of nematode eggs.',                  'cost_price' => 65.00,  'sell_price' => 88.00,  'quantity' => 22,  'base_unit' => 'bottle',  'low_stock_alert' => 4],
            ['name' => 'Bacillus firmus WP 1kg',       'category' => 'Nematicides',   'description' => 'Biological nematicide for root-knot nematode suppression.',                  'cost_price' => 55.00,  'sell_price' => 74.00,  'quantity' => 30,  'base_unit' => 'kg',      'low_stock_alert' => 5],

            // ── Rodenticides (5) ─────────────────────────────────────────────
            ['name' => 'Bromadiolone 0.005% Bait 1kg', 'category' => 'Rodenticides',  'description' => 'Second-generation anticoagulant rodenticide bait blocks.',                   'cost_price' => 18.00,  'sell_price' => 26.00,  'quantity' => 80,  'base_unit' => 'pack',    'low_stock_alert' => 15],
            ['name' => 'Brodifacoum 0.005% Bait 1kg',  'category' => 'Rodenticides',  'description' => 'Single-feed anticoagulant for rats and mice.',                               'cost_price' => 20.00,  'sell_price' => 28.00,  'quantity' => 70,  'base_unit' => 'pack',    'low_stock_alert' => 12],
            ['name' => 'Zinc Phosphide 80% WP 500g',   'category' => 'Rodenticides',  'description' => 'Acute toxicant for field rodent control.',                                   'cost_price' => 25.00,  'sell_price' => 35.00,  'quantity' => 50,  'base_unit' => 'pack',    'low_stock_alert' => 8],
            ['name' => 'Difethialone 0.0025% 1kg',     'category' => 'Rodenticides',  'description' => 'Second-generation anticoagulant rodenticide pellets.',                       'cost_price' => 22.00,  'sell_price' => 30.00,  'quantity' => 60,  'base_unit' => 'pack',    'low_stock_alert' => 10],
            ['name' => 'Flocoumafen 0.005% Bait 1kg',  'category' => 'Rodenticides',  'description' => 'Anticoagulant rodenticide for resistant rat populations.',                   'cost_price' => 24.00,  'sell_price' => 33.00,  'quantity' => 45,  'base_unit' => 'pack',    'low_stock_alert' => 8],

            // ── Adjuvants & Spreaders (10) ────────────────────────────────────
            ['name' => 'Non-Ionic Surfactant 1L',      'category' => 'Adjuvants',     'description' => 'Spreader-sticker for improved pesticide coverage.',                           'cost_price' => 15.00,  'sell_price' => 22.00,  'quantity' => 180, 'base_unit' => 'bottle',  'low_stock_alert' => 25],
            ['name' => 'Organosilicone Spreader 1L',   'category' => 'Adjuvants',     'description' => 'Supraspreader for foliar penetration and uptake.',                            'cost_price' => 22.00,  'sell_price' => 30.00,  'quantity' => 120, 'base_unit' => 'bottle',  'low_stock_alert' => 20],
            ['name' => 'Methylated Seed Oil 1L',       'category' => 'Adjuvants',     'description' => 'Crop oil concentrate for herbicide tank mixes.',                              'cost_price' => 18.00,  'sell_price' => 25.00,  'quantity' => 140, 'base_unit' => 'bottle',  'low_stock_alert' => 20],
            ['name' => 'pH Buffer Acidifier 1L',       'category' => 'Adjuvants',     'description' => 'Lowers spray water pH for optimal pesticide efficacy.',                       'cost_price' => 12.00,  'sell_price' => 18.00,  'quantity' => 160, 'base_unit' => 'bottle',  'low_stock_alert' => 25],
            ['name' => 'Drift Retardant 1L',           'category' => 'Adjuvants',     'description' => 'Reduces spray drift and evaporation during application.',                     'cost_price' => 20.00,  'sell_price' => 28.00,  'quantity' => 100, 'base_unit' => 'bottle',  'low_stock_alert' => 15],
            ['name' => 'Glyphosate Activator 1L',      'category' => 'Adjuvants',     'description' => 'Enhances glyphosate absorption through leaf cuticle.',                        'cost_price' => 16.00,  'sell_price' => 23.00,  'quantity' => 130, 'base_unit' => 'bottle',  'low_stock_alert' => 20],
            ['name' => 'Anti-Foam Agent 500ml',        'category' => 'Adjuvants',     'description' => 'Prevents excessive foam in spray tanks.',                                     'cost_price' => 10.00,  'sell_price' => 15.00,  'quantity' => 200, 'base_unit' => 'bottle',  'low_stock_alert' => 30],
            ['name' => 'Compatibility Agent 1L',       'category' => 'Adjuvants',     'description' => 'Prevents incompatibility in pesticide tank mixes.',                           'cost_price' => 14.00,  'sell_price' => 20.00,  'quantity' => 150, 'base_unit' => 'bottle',  'low_stock_alert' => 25],
            ['name' => 'Penetrant Plus 1L',            'category' => 'Adjuvants',     'description' => 'Systemic uptake enhancer for fungicides and insecticides.',                   'cost_price' => 18.00,  'sell_price' => 26.00,  'quantity' => 110, 'base_unit' => 'bottle',  'low_stock_alert' => 15],
            ['name' => 'Humectant Spreader 1L',        'category' => 'Adjuvants',     'description' => 'Slows drying to maximise contact time on foliage.',                           'cost_price' => 15.00,  'sell_price' => 22.00,  'quantity' => 120, 'base_unit' => 'bottle',  'low_stock_alert' => 20],

            // ── Soil Amendments (10) ──────────────────────────────────────────
            ['name' => 'Agricultural Lime 50kg',       'category' => 'Soil Amendments','description' => 'Raises soil pH and supplies calcium and magnesium.',                         'cost_price' => 45.00,  'sell_price' => 60.00,  'quantity' => 150, 'base_unit' => 'bag',     'low_stock_alert' => 25],
            ['name' => 'Dolomite Lime 50kg',           'category' => 'Soil Amendments','description' => 'Calcium-magnesium limestone for pH correction.',                             'cost_price' => 50.00,  'sell_price' => 67.00,  'quantity' => 120, 'base_unit' => 'bag',     'low_stock_alert' => 20],
            ['name' => 'Gypsum 50kg',                  'category' => 'Soil Amendments','description' => 'Soil conditioner for dispersive and saline soils.',                         'cost_price' => 48.00,  'sell_price' => 64.00,  'quantity' => 90,  'base_unit' => 'bag',     'low_stock_alert' => 15],
            ['name' => 'Biochar Fine 25kg',            'category' => 'Soil Amendments','description' => 'Activated biochar for soil carbon and water retention.',                     'cost_price' => 80.00,  'sell_price' => 107.00, 'quantity' => 40,  'base_unit' => 'bag',     'low_stock_alert' => 6],
            ['name' => 'Vermicompost 25kg',            'category' => 'Soil Amendments','description' => 'Worm castings for organic matter and microbial activity.',                   'cost_price' => 35.00,  'sell_price' => 48.00,  'quantity' => 80,  'base_unit' => 'bag',     'low_stock_alert' => 12],
            ['name' => 'Mycorrhiza WP 1kg',            'category' => 'Soil Amendments','description' => 'Arbuscular mycorrhizal fungi for root colonisation.',                        'cost_price' => 58.00,  'sell_price' => 78.00,  'quantity' => 50,  'base_unit' => 'kg',      'low_stock_alert' => 8],
            ['name' => 'Rhizobium Inoculant 500g',     'category' => 'Soil Amendments','description' => 'Nitrogen-fixing bacteria for legume seed treatment.',                        'cost_price' => 22.00,  'sell_price' => 31.00,  'quantity' => 100, 'base_unit' => 'pack',    'low_stock_alert' => 15],
            ['name' => 'Potassium Silicate 1L',        'category' => 'Soil Amendments','description' => 'Liquid silicon for soil pH buffering and plant resistance.',                  'cost_price' => 28.00,  'sell_price' => 38.00,  'quantity' => 80,  'base_unit' => 'bottle',  'low_stock_alert' => 12],
            ['name' => 'Bentonite Clay 50kg',          'category' => 'Soil Amendments','description' => 'Improves water and nutrient retention in sandy soils.',                      'cost_price' => 40.00,  'sell_price' => 54.00,  'quantity' => 60,  'base_unit' => 'bag',     'low_stock_alert' => 10],
            ['name' => 'Sulphur 90% WG 25kg',         'category' => 'Soil Amendments','description' => 'Acidifies soil pH and supplies sulphur for brassicas.',                      'cost_price' => 65.00,  'sell_price' => 87.00,  'quantity' => 45,  'base_unit' => 'bag',     'low_stock_alert' => 7],
        ];

        // Build rows with timestamps
        $rows = array_map(fn($p) => array_merge($p, [
            'created_at' => $now,
            'updated_at' => $now,
        ]), $products);

        // Insert in chunks to avoid packet-size issues
        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('products')->insertOrIgnore($chunk);
        }
    }
}
