<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class WholesaleProductSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $products = [
            // ── Herbicides (25) ──────────────────────────────────────────────
            ['name' => 'Glyphosate 360 SL 20L',         'category' => 'Herbicides',     'description' => 'Systemic non-selective herbicide — bulk 20-litre drum.',                    'cost_price' => 480.00,  'sell_price' => 630.00,  'quantity' => 80,  'base_unit' => 'drum',    'low_stock_alert' => 10],
            ['name' => 'Paraquat 200 SL 20L',           'category' => 'Herbicides',     'description' => 'Fast-acting contact herbicide — bulk 20-litre drum.',                       'cost_price' => 560.00,  'sell_price' => 740.00,  'quantity' => 50,  'base_unit' => 'drum',    'low_stock_alert' => 8],
            ['name' => 'Atrazine 500 SC 20L',           'category' => 'Herbicides',     'description' => 'Selective pre-emergent herbicide for maize — bulk drum.',                   'cost_price' => 420.00,  'sell_price' => 556.00,  'quantity' => 45,  'base_unit' => 'drum',    'low_stock_alert' => 6],
            ['name' => 'Pendimethalin 330 EC 20L',      'category' => 'Herbicides',     'description' => 'Pre-emergent herbicide — bulk 20-litre drum.',                              'cost_price' => 640.00,  'sell_price' => 847.00,  'quantity' => 35,  'base_unit' => 'drum',    'low_stock_alert' => 5],
            ['name' => '2,4-D Amine 720 SL 20L',       'category' => 'Herbicides',     'description' => 'Selective post-emergent broadleaf herbicide — bulk drum.',                   'cost_price' => 380.00,  'sell_price' => 503.00,  'quantity' => 60,  'base_unit' => 'drum',    'low_stock_alert' => 8],
            ['name' => 'Butachlor 50 EC 20L',           'category' => 'Herbicides',     'description' => 'Selective pre-emergent for rice — bulk 20L.',                               'cost_price' => 520.00,  'sell_price' => 688.00,  'quantity' => 28,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'Metolachlor 960 EC 20L',        'category' => 'Herbicides',     'description' => 'Pre-emergent grass herbicide — bulk 20L drum.',                             'cost_price' => 700.00,  'sell_price' => 927.00,  'quantity' => 20,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Oxyfluorfen 240 EC 20L',        'category' => 'Herbicides',     'description' => 'Pre-emergent herbicide for alliums — 20L drum.',                            'cost_price' => 740.00,  'sell_price' => 979.00,  'quantity' => 18,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Propanil 360 EC 20L',           'category' => 'Herbicides',     'description' => 'Post-emergent rice herbicide — 20L bulk drum.',                             'cost_price' => 490.00,  'sell_price' => 648.00,  'quantity' => 30,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'Diuron 80 WP 25kg',             'category' => 'Herbicides',     'description' => 'Residual herbicide for sugarcane — 25kg sack.',                             'cost_price' => 820.00,  'sell_price' => 1085.00, 'quantity' => 20,  'base_unit' => 'sack',    'low_stock_alert' => 3],
            ['name' => 'Fluazifop-p-butyl 150 EC 20L',  'category' => 'Herbicides',     'description' => 'Post-emergent grass herbicide — 20L drum.',                                 'cost_price' => 950.00,  'sell_price' => 1257.00, 'quantity' => 15,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Clethodim 240 EC 20L',          'category' => 'Herbicides',     'description' => 'Post-emergent grass herbicide for broadleaf crops — 20L.',                  'cost_price' => 880.00,  'sell_price' => 1164.00, 'quantity' => 15,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Dicamba 480 SL 20L',            'category' => 'Herbicides',     'description' => 'Broadleaf weed control in cereals — 20L drum.',                             'cost_price' => 600.00,  'sell_price' => 794.00,  'quantity' => 22,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Metribuzin 70 WP 25kg',         'category' => 'Herbicides',     'description' => 'Pre and post-emergent potatoes herbicide — 25kg pack.',                     'cost_price' => 950.00,  'sell_price' => 1257.00, 'quantity' => 12,  'base_unit' => 'sack',    'low_stock_alert' => 2],
            ['name' => 'Trifluralin 480 EC 20L',        'category' => 'Herbicides',     'description' => 'Pre-plant incorporated herbicide — 20L drum.',                              'cost_price' => 470.00,  'sell_price' => 622.00,  'quantity' => 30,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'Imazapic 240 SL 20L',           'category' => 'Herbicides',     'description' => 'Selective herbicide for sugar cane — 20L drum.',                            'cost_price' => 1100.00, 'sell_price' => 1455.00, 'quantity' => 10,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Haloxyfop-P 108 EC 20L',        'category' => 'Herbicides',     'description' => 'Systemic grass herbicide — 20L bulk drum.',                                 'cost_price' => 1050.00, 'sell_price' => 1390.00, 'quantity' => 12,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Quizalofop-p-ethyl 50 EC 20L',  'category' => 'Herbicides',     'description' => 'Grass herbicide for soybeans/cotton — 20L.',                                'cost_price' => 1000.00, 'sell_price' => 1323.00, 'quantity' => 12,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Sethoxydim 187 EC 20L',         'category' => 'Herbicides',     'description' => 'Selective post-emergent grass herbicide — 20L drum.',                       'cost_price' => 800.00,  'sell_price' => 1059.00, 'quantity' => 15,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Linuron 450 SC 20L',            'category' => 'Herbicides',     'description' => 'Residual herbicide for root vegetables — 20L drum.',                        'cost_price' => 620.00,  'sell_price' => 820.00,  'quantity' => 18,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Terbutryn 500 SC 20L',          'category' => 'Herbicides',     'description' => 'Pre-emergent herbicide for cereals — bulk 20L.',                            'cost_price' => 530.00,  'sell_price' => 701.00,  'quantity' => 22,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Ametryn 500 SC 20L',            'category' => 'Herbicides',     'description' => 'Selective herbicide for sugarcane — 20L drum.',                             'cost_price' => 560.00,  'sell_price' => 741.00,  'quantity' => 20,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Benfluralin 1.5 G 200kg',       'category' => 'Herbicides',     'description' => 'Granular pre-emergent herbicide — big bag 200kg.',                          'cost_price' => 900.00,  'sell_price' => 1191.00, 'quantity' => 8,   'base_unit' => 'big-bag', 'low_stock_alert' => 1],
            ['name' => 'Halosulfuron 75 WG 1kg',        'category' => 'Herbicides',     'description' => 'Post-emergent selective for nutsedge — 1kg pack.',                          'cost_price' => 380.00,  'sell_price' => 503.00,  'quantity' => 25,  'base_unit' => 'kg',      'low_stock_alert' => 4],
            ['name' => 'Diuron + Paraquat 200L',        'category' => 'Herbicides',     'description' => 'Premix total herbicide for non-crop areas — 200L IBC.',                     'cost_price' => 3500.00, 'sell_price' => 4632.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],

            // ── Fungicides (25) ──────────────────────────────────────────────
            ['name' => 'Mancozeb 80 WP 25kg',           'category' => 'Fungicides',     'description' => 'Broad-spectrum protective fungicide — 25kg drum.',                          'cost_price' => 380.00,  'sell_price' => 503.00,  'quantity' => 80,  'base_unit' => 'drum',    'low_stock_alert' => 12],
            ['name' => 'Metalaxyl-M 350 ES 20L',        'category' => 'Fungicides',     'description' => 'Systemic fungicide for Pythium seed treatment — 20L.',                      'cost_price' => 1200.00, 'sell_price' => 1588.00, 'quantity' => 15,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Propiconazole 250 EC 20L',      'category' => 'Fungicides',     'description' => 'Systemic triazole fungicide — 20L drum.',                                   'cost_price' => 1000.00, 'sell_price' => 1323.00, 'quantity' => 20,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Azoxystrobin 250 SC 20L',       'category' => 'Fungicides',     'description' => 'Broad-spectrum strobilurin — 20L bulk drum.',                               'cost_price' => 1320.00, 'sell_price' => 1746.00, 'quantity' => 15,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Tebuconazole 250 EW 20L',       'category' => 'Fungicides',     'description' => 'Systemic triazole for cereals and vegetables — 20L drum.',                  'cost_price' => 1060.00, 'sell_price' => 1403.00, 'quantity' => 16,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Thiram 75 WP 25kg',             'category' => 'Fungicides',     'description' => 'Protective fungicide and seed dressing — 25kg drum.',                       'cost_price' => 440.00,  'sell_price' => 582.00,  'quantity' => 40,  'base_unit' => 'drum',    'low_stock_alert' => 6],
            ['name' => 'Captan 50 WP 25kg',             'category' => 'Fungicides',     'description' => 'Contact fungicide for tubers and fruits — 25kg sack.',                      'cost_price' => 500.00,  'sell_price' => 661.00,  'quantity' => 35,  'base_unit' => 'sack',    'low_stock_alert' => 5],
            ['name' => 'Carbendazim 500 SC 20L',        'category' => 'Fungicides',     'description' => 'Broad-spectrum systemic benzimidazole — 20L drum.',                         'cost_price' => 640.00,  'sell_price' => 847.00,  'quantity' => 30,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'Chlorothalonil 720 SC 20L',     'category' => 'Fungicides',     'description' => 'Multipurpose contact fungicide — 20L bulk drum.',                           'cost_price' => 540.00,  'sell_price' => 714.00,  'quantity' => 35,  'base_unit' => 'drum',    'low_stock_alert' => 5],
            ['name' => 'Iprodione 500 SC 20L',          'category' => 'Fungicides',     'description' => 'Contact fungicide Botrytis / Sclerotinia — 20L drum.',                      'cost_price' => 880.00,  'sell_price' => 1164.00, 'quantity' => 18,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Cymoxanil 45 WP 25kg',          'category' => 'Fungicides',     'description' => 'Systemic late blight fungicide — 25kg pack.',                               'cost_price' => 900.00,  'sell_price' => 1191.00, 'quantity' => 15,  'base_unit' => 'sack',    'low_stock_alert' => 2],
            ['name' => 'Dimethomorph 50 WP 25kg',       'category' => 'Fungicides',     'description' => 'Oomycide for downy mildew — 25kg pack.',                                    'cost_price' => 1200.00, 'sell_price' => 1588.00, 'quantity' => 12,  'base_unit' => 'sack',    'low_stock_alert' => 2],
            ['name' => 'Fosetyl-Al 80 WP 25kg',         'category' => 'Fungicides',     'description' => 'Systemic fungicide for Phytophthora — 25kg drum.',                          'cost_price' => 950.00,  'sell_price' => 1257.00, 'quantity' => 14,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Hexaconazole 50 SC 20L',        'category' => 'Fungicides',     'description' => 'Systemic triazole for rice diseases — 20L drum.',                           'cost_price' => 900.00,  'sell_price' => 1191.00, 'quantity' => 18,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Difenoconazole 250 EC 20L',     'category' => 'Fungicides',     'description' => 'Broad-spectrum triazole fungicide — 20L drum.',                             'cost_price' => 1080.00, 'sell_price' => 1429.00, 'quantity' => 14,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Kresoxim-methyl 500 SC 20L',    'category' => 'Fungicides',     'description' => 'Strobilurin for powdery mildew and scab — 20L drum.',                       'cost_price' => 1240.00, 'sell_price' => 1641.00, 'quantity' => 10,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Trifloxystrobin 500 WG 5kg',   'category' => 'Fungicides',     'description' => 'Broad-spectrum strobilurin — 5kg container.',                               'cost_price' => 1650.00, 'sell_price' => 2184.00, 'quantity' => 8,   'base_unit' => 'can',     'low_stock_alert' => 1],
            ['name' => 'Fludioxonil 25 FS 20L',         'category' => 'Fungicides',     'description' => 'Phenylpyrrole seed treatment fungicide — 20L drum.',                        'cost_price' => 1300.00, 'sell_price' => 1720.00, 'quantity' => 10,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Epoxiconazole 125 SC 20L',      'category' => 'Fungicides',     'description' => 'Systemic triazole for cereal diseases — 20L drum.',                         'cost_price' => 1140.00, 'sell_price' => 1508.00, 'quantity' => 12,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Myclobutanil 190 EW 20L',       'category' => 'Fungicides',     'description' => 'Systemic fungicide for powdery mildew — 20L drum.',                         'cost_price' => 1180.00, 'sell_price' => 1562.00, 'quantity' => 10,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Penconazole 100 EC 20L',        'category' => 'Fungicides',     'description' => 'Systemic triazole for grapes/apples — 20L drum.',                           'cost_price' => 1000.00, 'sell_price' => 1323.00, 'quantity' => 12,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Mancozeb + Metalaxyl 70 WP 25kg','category' => 'Fungicides',   'description' => 'Systemic + protectant premix for late blight — 25kg.',                      'cost_price' => 700.00,  'sell_price' => 926.00,  'quantity' => 25,  'base_unit' => 'sack',    'low_stock_alert' => 4],
            ['name' => 'Triadimefon 250 WP 25kg',       'category' => 'Fungicides',     'description' => 'Triazole for rusts and powdery mildew — 25kg sack.',                        'cost_price' => 950.00,  'sell_price' => 1257.00, 'quantity' => 10,  'base_unit' => 'sack',    'low_stock_alert' => 2],
            ['name' => 'Paclobutrazol 250 SC 20L',      'category' => 'Fungicides',     'description' => 'Triazole fungicide / PGR for mango — 20L drum.',                            'cost_price' => 1450.00, 'sell_price' => 1919.00, 'quantity' => 8,   'base_unit' => 'drum',    'low_stock_alert' => 1],
            ['name' => 'Vinclozolin 500 SC 20L',        'category' => 'Fungicides',     'description' => 'Contact fungicide for grey mould — 20L drum.',                              'cost_price' => 840.00,  'sell_price' => 1112.00, 'quantity' => 14,  'base_unit' => 'drum',    'low_stock_alert' => 2],

            // ── Insecticides (30) ─────────────────────────────────────────────
            ['name' => 'Lambda-cyhalothrin 25 EC 20L',  'category' => 'Insecticides',   'description' => 'Broad-spectrum pyrethroid — 20L bulk drum.',                                'cost_price' => 580.00,  'sell_price' => 767.00,  'quantity' => 60,  'base_unit' => 'drum',    'low_stock_alert' => 8],
            ['name' => 'Cypermethrin 200 EC 20L',       'category' => 'Insecticides',   'description' => 'Broad-spectrum pyrethroid — 20L bulk drum.',                                'cost_price' => 500.00,  'sell_price' => 661.00,  'quantity' => 70,  'base_unit' => 'drum',    'low_stock_alert' => 10],
            ['name' => 'Chlorpyrifos 480 EC 20L',       'category' => 'Insecticides',   'description' => 'Organophosphate against soil insects — 20L drum.',                          'cost_price' => 440.00,  'sell_price' => 582.00,  'quantity' => 65,  'base_unit' => 'drum',    'low_stock_alert' => 10],
            ['name' => 'Dimethoate 400 EC 20L',         'category' => 'Insecticides',   'description' => 'Systemic OP for sucking pests — 20L drum.',                                 'cost_price' => 420.00,  'sell_price' => 556.00,  'quantity' => 55,  'base_unit' => 'drum',    'low_stock_alert' => 8],
            ['name' => 'Imidacloprid 200 SL 20L',       'category' => 'Insecticides',   'description' => 'Systemic neonicotinoid for sucking insects — 20L drum.',                    'cost_price' => 960.00,  'sell_price' => 1270.00, 'quantity' => 40,  'base_unit' => 'drum',    'low_stock_alert' => 5],
            ['name' => 'Thiamethoxam 240 SC 20L',       'category' => 'Insecticides',   'description' => 'Systemic neonicotinoid — 20L bulk drum.',                                   'cost_price' => 1060.00, 'sell_price' => 1403.00, 'quantity' => 30,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'Fipronil 200 SC 20L',           'category' => 'Insecticides',   'description' => 'Phenylpyrazole for borers and termites — 20L drum.',                        'cost_price' => 1000.00, 'sell_price' => 1323.00, 'quantity' => 25,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'Emamectin Benzoate 19 EC 20L',  'category' => 'Insecticides',   'description' => 'Avermectin for caterpillars and leafminers — 20L drum.',                    'cost_price' => 1100.00, 'sell_price' => 1455.00, 'quantity' => 22,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Spinosad 480 SC 20L',           'category' => 'Insecticides',   'description' => 'Biological insecticide for lepidoptera — 20L drum.',                        'cost_price' => 1320.00, 'sell_price' => 1746.00, 'quantity' => 16,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Abamectin 18 EC 20L',           'category' => 'Insecticides',   'description' => 'Biological insecticide/miticide — 20L drum.',                               'cost_price' => 1240.00, 'sell_price' => 1641.00, 'quantity' => 18,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Deltamethrin 25 EC 20L',        'category' => 'Insecticides',   'description' => 'Pyrethroid for stored products/field crops — 20L drum.',                    'cost_price' => 540.00,  'sell_price' => 714.00,  'quantity' => 45,  'base_unit' => 'drum',    'low_stock_alert' => 6],
            ['name' => 'Bifenthrin 100 EC 20L',         'category' => 'Insecticides',   'description' => 'Broad-spectrum pyrethroid with residual action — 20L.',                     'cost_price' => 760.00,  'sell_price' => 1006.00, 'quantity' => 30,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'Profenofos 500 EC 20L',         'category' => 'Insecticides',   'description' => 'Contact/systemic OP for cotton bollworm — 20L drum.',                       'cost_price' => 700.00,  'sell_price' => 926.00,  'quantity' => 30,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'Malathion 500 EC 20L',          'category' => 'Insecticides',   'description' => 'Non-systemic OP for broad insect control — 20L drum.',                      'cost_price' => 360.00,  'sell_price' => 476.00,  'quantity' => 60,  'base_unit' => 'drum',    'low_stock_alert' => 8],
            ['name' => 'Triazophos 400 EC 20L',         'category' => 'Insecticides',   'description' => 'OP against caterpillars and mites on rice — 20L drum.',                     'cost_price' => 600.00,  'sell_price' => 794.00,  'quantity' => 28,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'Carbaryl 850 WP 25kg',          'category' => 'Insecticides',   'description' => 'Carbamate insecticide for chewing insects — 25kg drum.',                    'cost_price' => 580.00,  'sell_price' => 767.00,  'quantity' => 35,  'base_unit' => 'drum',    'low_stock_alert' => 5],
            ['name' => 'Indoxacarb 150 SC 20L',         'category' => 'Insecticides',   'description' => 'Oxadiazine for caterpillars in vegetables — 20L drum.',                     'cost_price' => 1200.00, 'sell_price' => 1588.00, 'quantity' => 14,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Chlorfenapyr 360 SC 20L',       'category' => 'Insecticides',   'description' => 'Pyrrole insecticide for diamondback moth — 20L drum.',                      'cost_price' => 1280.00, 'sell_price' => 1694.00, 'quantity' => 12,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Clothianidin 600 FS 20L',       'category' => 'Insecticides',   'description' => 'Neonicotinoid seed treatment — 20L drum.',                                  'cost_price' => 1180.00, 'sell_price' => 1562.00, 'quantity' => 15,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Acetamiprid 200 SP 10kg',       'category' => 'Insecticides',   'description' => 'Neonicotinoid for whitefly, thrips, aphids — 10kg.',                        'cost_price' => 3200.00, 'sell_price' => 4233.00, 'quantity' => 8,   'base_unit' => 'can',     'low_stock_alert' => 1],
            ['name' => 'Permethrin 500 EC 20L',         'category' => 'Insecticides',   'description' => 'Pyrethroid for cotton and stored grain — 20L drum.',                        'cost_price' => 640.00,  'sell_price' => 847.00,  'quantity' => 35,  'base_unit' => 'drum',    'low_stock_alert' => 5],
            ['name' => 'Methomyl 90 SP 10kg',           'category' => 'Insecticides',   'description' => 'Systemic carbamate for caterpillars and flies — 10kg.',                     'cost_price' => 800.00,  'sell_price' => 1059.00, 'quantity' => 18,  'base_unit' => 'can',     'low_stock_alert' => 3],
            ['name' => 'Novaluron 100 EC 20L',          'category' => 'Insecticides',   'description' => 'IGR for whitefly and leafminer larvae — 20L drum.',                         'cost_price' => 1320.00, 'sell_price' => 1746.00, 'quantity' => 10,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Spiromesifen 240 SC 20L',       'category' => 'Insecticides',   'description' => 'Lipid biosynthesis inhibitor for mites/whitefly — 20L.',                    'cost_price' => 1380.00, 'sell_price' => 1826.00, 'quantity' => 8,   'base_unit' => 'drum',    'low_stock_alert' => 1],
            ['name' => 'Pyriproxyfen 100 EC 20L',       'category' => 'Insecticides',   'description' => 'JHA IGR for whitefly and scale — 20L drum.',                                'cost_price' => 1100.00, 'sell_price' => 1455.00, 'quantity' => 12,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Lufenuron 050 EC 20L',          'category' => 'Insecticides',   'description' => 'IGR for caterpillars — 20L bulk drum.',                                     'cost_price' => 1240.00, 'sell_price' => 1641.00, 'quantity' => 10,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Hexythiazox 100 EC 20L',        'category' => 'Insecticides',   'description' => 'Selective miticide for eggs/early stages — 20L drum.',                      'cost_price' => 1060.00, 'sell_price' => 1403.00, 'quantity' => 12,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Cyflumetofen 200 SC 20L',       'category' => 'Insecticides',   'description' => 'Novel complex II miticide for tetranychid mites — 20L.',                    'cost_price' => 1500.00, 'sell_price' => 1985.00, 'quantity' => 8,   'base_unit' => 'drum',    'low_stock_alert' => 1],
            ['name' => 'Teflubenzuron 150 SC 20L',      'category' => 'Insecticides',   'description' => 'Benzoylurea IGR for lepidopteran control — 20L drum.',                      'cost_price' => 1160.00, 'sell_price' => 1535.00, 'quantity' => 10,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Phosmet 50 WP 25kg',            'category' => 'Insecticides',   'description' => 'OP for codling moth in fruits — 25kg sack.',                                'cost_price' => 1100.00, 'sell_price' => 1455.00, 'quantity' => 10,  'base_unit' => 'sack',    'low_stock_alert' => 2],

            // ── Fertilizers (25) ─────────────────────────────────────────────
            ['name' => 'NPK 15-15-15 1000kg',           'category' => 'Fertilizers',    'description' => 'Balanced compound fertilizer — bulk 1-tonne bag.',                          'cost_price' => 2600.00, 'sell_price' => 3441.00, 'quantity' => 30,  'base_unit' => 'tonne',   'low_stock_alert' => 5],
            ['name' => 'NPK 20-10-10 1000kg',           'category' => 'Fertilizers',    'description' => 'High-N compound fertilizer — 1-tonne bag.',                                 'cost_price' => 2700.00, 'sell_price' => 3573.00, 'quantity' => 25,  'base_unit' => 'tonne',   'low_stock_alert' => 4],
            ['name' => 'Urea 46% N 1000kg',             'category' => 'Fertilizers',    'description' => 'High-nitrogen fertilizer for topdressing — 1-tonne bag.',                   'cost_price' => 2400.00, 'sell_price' => 3176.00, 'quantity' => 28,  'base_unit' => 'tonne',   'low_stock_alert' => 4],
            ['name' => 'CAN 26% N 1000kg',              'category' => 'Fertilizers',    'description' => 'Calcium ammonium nitrate — 1-tonne bag.',                                   'cost_price' => 2200.00, 'sell_price' => 2912.00, 'quantity' => 22,  'base_unit' => 'tonne',   'low_stock_alert' => 3],
            ['name' => 'DAP 18-46-0 1000kg',            'category' => 'Fertilizers',    'description' => 'Di-ammonium phosphate — 1-tonne bag.',                                      'cost_price' => 2850.00, 'sell_price' => 3771.00, 'quantity' => 20,  'base_unit' => 'tonne',   'low_stock_alert' => 3],
            ['name' => 'MOP 60% K2O 1000kg',            'category' => 'Fertilizers',    'description' => 'Muriate of potash — bulk 1-tonne bag.',                                     'cost_price' => 2700.00, 'sell_price' => 3573.00, 'quantity' => 18,  'base_unit' => 'tonne',   'low_stock_alert' => 3],
            ['name' => 'Single Super Phosphate 1000kg', 'category' => 'Fertilizers',    'description' => 'SSP for basal phosphate/sulphur supply — 1-tonne.',                          'cost_price' => 2000.00, 'sell_price' => 2647.00, 'quantity' => 15,  'base_unit' => 'tonne',   'low_stock_alert' => 2],
            ['name' => 'Ammonium Sulphate 1000kg',      'category' => 'Fertilizers',    'description' => 'Nitrogen and sulphur fertilizer — bulk 1-tonne bag.',                       'cost_price' => 2100.00, 'sell_price' => 2779.00, 'quantity' => 18,  'base_unit' => 'tonne',   'low_stock_alert' => 3],
            ['name' => 'Zinc Sulphate 21% 1000kg',      'category' => 'Fertilizers',    'description' => 'Zinc source for soil — bulk 1-tonne bag.',                                  'cost_price' => 2400.00, 'sell_price' => 3176.00, 'quantity' => 12,  'base_unit' => 'tonne',   'low_stock_alert' => 2],
            ['name' => 'Borax 11% B 1000kg',            'category' => 'Fertilizers',    'description' => 'Boron source — bulk 1-tonne bag.',                                          'cost_price' => 2100.00, 'sell_price' => 2779.00, 'quantity' => 10,  'base_unit' => 'tonne',   'low_stock_alert' => 2],
            ['name' => 'Calcium Nitrate 15.5% N 1000kg','category' => 'Fertilizers',   'description' => 'Water-soluble Ca-N for fertigation — 1-tonne bag.',                          'cost_price' => 3000.00, 'sell_price' => 3970.00, 'quantity' => 12,  'base_unit' => 'tonne',   'low_stock_alert' => 2],
            ['name' => 'Potassium Nitrate 13-0-46 1000kg','category' => 'Fertilizers', 'description' => 'Chloride-free NK for fertigation — 1-tonne bag.',                            'cost_price' => 3600.00, 'sell_price' => 4764.00, 'quantity' => 8,   'base_unit' => 'tonne',   'low_stock_alert' => 1],
            ['name' => 'Foliar Fertilizer Amino 200L',  'category' => 'Fertilizers',    'description' => 'Amino-acid foliar feed — 200L IBC tank.',                                   'cost_price' => 3800.00, 'sell_price' => 5029.00, 'quantity' => 6,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Micronutrient Mix Foliar 200L', 'category' => 'Fertilizers',    'description' => 'Complete micro-nutrient spray — 200L IBC.',                                  'cost_price' => 6500.00, 'sell_price' => 8600.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Humic Acid 70% 25kg',           'category' => 'Fertilizers',    'description' => 'Soil conditioner and biostimulant — bulk 25kg pack.',                        'cost_price' => 800.00,  'sell_price' => 1059.00, 'quantity' => 30,  'base_unit' => 'pack',    'low_stock_alert' => 4],
            ['name' => 'Seaweed Extract SL 200L',       'category' => 'Fertilizers',    'description' => 'Biostimulant for yield and stress — 200L IBC.',                             'cost_price' => 4800.00, 'sell_price' => 6353.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Potassium Humate 200L',         'category' => 'Fertilizers',    'description' => 'Liquid humate for soil structure — 200L IBC.',                               'cost_price' => 4200.00, 'sell_price' => 5559.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Magnesium Sulphate 1000kg',     'category' => 'Fertilizers',    'description' => 'Kieserite for Mg/S deficiency — 1-tonne bag.',                              'cost_price' => 2200.00, 'sell_price' => 2912.00, 'quantity' => 10,  'base_unit' => 'tonne',   'low_stock_alert' => 2],
            ['name' => 'Sulphate of Potash 50% 1000kg', 'category' => 'Fertilizers',    'description' => 'Chloride-free potassium for sensitive crops — tonne.',                       'cost_price' => 4200.00, 'sell_price' => 5559.00, 'quantity' => 8,   'base_unit' => 'tonne',   'low_stock_alert' => 1],
            ['name' => 'Organic Compost Granule 1000kg','category' => 'Fertilizers',    'description' => 'Composted organic matter — 1-tonne flex bag.',                               'cost_price' => 1400.00, 'sell_price' => 1853.00, 'quantity' => 20,  'base_unit' => 'tonne',   'low_stock_alert' => 3],
            ['name' => 'NPK 12-12-17 + 2MgO 1000kg',   'category' => 'Fertilizers',    'description' => 'Turf/vegetable granular fertilizer — 1-tonne bag.',                          'cost_price' => 2800.00, 'sell_price' => 3706.00, 'quantity' => 12,  'base_unit' => 'tonne',   'low_stock_alert' => 2],
            ['name' => 'Ferrous Sulphate 20% Fe 1000kg','category' => 'Fertilizers',   'description' => 'Corrects iron chlorosis — bulk 1-tonne bag.',                               'cost_price' => 2100.00, 'sell_price' => 2779.00, 'quantity' => 8,   'base_unit' => 'tonne',   'low_stock_alert' => 1],
            ['name' => 'Manganese Sulphate 32% 1000kg', 'category' => 'Fertilizers',    'description' => 'Manganese source — bulk 1-tonne bag.',                                      'cost_price' => 2300.00, 'sell_price' => 3044.00, 'quantity' => 8,   'base_unit' => 'tonne',   'low_stock_alert' => 1],
            ['name' => 'Copper Sulphate 25% 1000kg',    'category' => 'Fertilizers',    'description' => 'Copper deficiency correction — bulk 1-tonne bag.',                           'cost_price' => 2500.00, 'sell_price' => 3309.00, 'quantity' => 6,   'base_unit' => 'tonne',   'low_stock_alert' => 1],
            ['name' => 'Silicon Fertilizer SL 200L',    'category' => 'Fertilizers',    'description' => 'Silicon for cell wall strengthening — 200L IBC.',                           'cost_price' => 4500.00, 'sell_price' => 5956.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],

            // ── Growth Regulators (15) ───────────────────────────────────────
            ['name' => 'Gibberellic Acid 20% SP 1kg',   'category' => 'Growth Regulators','description' => 'Promotes stem elongation and fruit setting — 1kg pack.',                  'cost_price' => 1200.00, 'sell_price' => 1588.00, 'quantity' => 15,  'base_unit' => 'kg',      'low_stock_alert' => 2],
            ['name' => 'Cytokinin 40 SL 200L',          'category' => 'Growth Regulators','description' => 'Promotes branching and fruit retention — 200L IBC.',                       'cost_price' => 5500.00, 'sell_price' => 7279.00, 'quantity' => 4,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Ethephon 480 SL 20L',           'category' => 'Growth Regulators','description' => 'Ethylene-releasing compound — 20L drum.',                                 'cost_price' => 640.00,  'sell_price' => 847.00,  'quantity' => 28,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'Trinexapac-ethyl 250 SC 20L',   'category' => 'Growth Regulators','description' => 'Lodging prevention retardant for cereals — 20L.',                         'cost_price' => 1000.00, 'sell_price' => 1323.00, 'quantity' => 16,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Mepiquat Chloride 50 SL 20L',   'category' => 'Growth Regulators','description' => 'PGR for cotton canopy management — 20L drum.',                            'cost_price' => 760.00,  'sell_price' => 1006.00, 'quantity' => 18,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Chlormequat Chloride 460 SL 20L','category' => 'Growth Regulators','description' => 'Stem shortener for cereals — 20L drum.',                                 'cost_price' => 700.00,  'sell_price' => 926.00,  'quantity' => 20,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => '1-MCP Sachet 3.3% 100g',        'category' => 'Growth Regulators','description' => '1-MCP for post-harvest ethylene blocking — 100g pack.',                   'cost_price' => 150.00,  'sell_price' => 199.00,  'quantity' => 80,  'base_unit' => 'pack',    'low_stock_alert' => 10],
            ['name' => 'IAA Root Enhancer 200L',        'category' => 'Growth Regulators','description' => 'IAA for rooting and transplant establishment — 200L IBC.',                'cost_price' => 4800.00, 'sell_price' => 6353.00, 'quantity' => 4,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'IBA Rooting Powder 3000ppm 5kg','category' => 'Growth Regulators','description' => 'IBA for vegetative cuttings — 5kg container.',                            'cost_price' => 1500.00, 'sell_price' => 1985.00, 'quantity' => 8,   'base_unit' => 'can',     'low_stock_alert' => 1],
            ['name' => 'NAA 4.5% SL 20L',              'category' => 'Growth Regulators','description' => 'NAA for fruit thinning and rooting — 20L drum.',                          'cost_price' => 640.00,  'sell_price' => 847.00,  'quantity' => 22,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Brassinolide 0.01% SL 20L',    'category' => 'Growth Regulators','description' => 'Brassinosteroid for stress tolerance — 20L drum.',                        'cost_price' => 1060.00, 'sell_price' => 1403.00, 'quantity' => 12,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Triacontanol 0.1% EW 20L',     'category' => 'Growth Regulators','description' => 'Natural growth promoter for photosynthesis — 20L drum.',                  'cost_price' => 500.00,  'sell_price' => 661.00,  'quantity' => 25,  'base_unit' => 'drum',    'low_stock_alert' => 4],
            ['name' => 'CPPU Cytokinin 10 SL 20L',      'category' => 'Growth Regulators','description' => 'Forchlorfenuron for fruit enlargement — 20L drum.',                       'cost_price' => 1240.00, 'sell_price' => 1641.00, 'quantity' => 10,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Prohexadione-Ca 10 WP 25kg',    'category' => 'Growth Regulators','description' => 'Lodging prevention in rice/wheat — 25kg pack.',                           'cost_price' => 1100.00, 'sell_price' => 1455.00, 'quantity' => 8,   'base_unit' => 'sack',    'low_stock_alert' => 1],
            ['name' => 'Daminozide 850 WP 25kg',        'category' => 'Growth Regulators','description' => 'Growth retardant — 25kg drum.',                                           'cost_price' => 1200.00, 'sell_price' => 1588.00, 'quantity' => 6,   'base_unit' => 'drum',    'low_stock_alert' => 1],

            // ── Nematicides (10) ──────────────────────────────────────────────
            ['name' => 'Carbosulfan 200 CS 20L',        'category' => 'Nematicides',    'description' => 'Seed treatment nematicide — 20L drum.',                                     'cost_price' => 1000.00, 'sell_price' => 1323.00, 'quantity' => 18,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Terbufos 15 G 200kg',           'category' => 'Nematicides',    'description' => 'Soil granule nematicide — bulk 200kg big-bag.',                             'cost_price' => 1600.00, 'sell_price' => 2118.00, 'quantity' => 12,  'base_unit' => 'big-bag', 'low_stock_alert' => 2],
            ['name' => 'Cadusafos 10 G 200kg',          'category' => 'Nematicides',    'description' => 'OP nematicide granules — bulk 200kg big-bag.',                              'cost_price' => 1800.00, 'sell_price' => 2382.00, 'quantity' => 10,  'base_unit' => 'big-bag', 'low_stock_alert' => 2],
            ['name' => 'Fosthiazate 150 SC 20L',        'category' => 'Nematicides',    'description' => 'Systemic nematicide — 20L drum.',                                           'cost_price' => 1550.00, 'sell_price' => 2051.00, 'quantity' => 12,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Fluopyram 500 SC 20L',          'category' => 'Nematicides',    'description' => 'SDHI fungicide/nematicide — 20L drum.',                                     'cost_price' => 2000.00, 'sell_price' => 2647.00, 'quantity' => 8,   'base_unit' => 'drum',    'low_stock_alert' => 1],
            ['name' => 'Oxamyl 24% SL 20L',             'category' => 'Nematicides',    'description' => 'Systemic carbamate nematicide — 20L drum.',                                 'cost_price' => 1320.00, 'sell_price' => 1746.00, 'quantity' => 14,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Dazomet 98% GR 200kg',          'category' => 'Nematicides',    'description' => 'Soil fumigant for nematodes/fungi — 200kg big-bag.',                        'cost_price' => 3200.00, 'sell_price' => 4233.00, 'quantity' => 6,   'base_unit' => 'big-bag', 'low_stock_alert' => 1],
            ['name' => 'Dimethyl Disulphide 200L',      'category' => 'Nematicides',    'description' => 'Biofumigant for soil nematodes — 200L IBC.',                                'cost_price' => 17000.00,'sell_price' => 22500.00,'quantity' => 3,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Purpureocillium lilacinum 20L', 'category' => 'Nematicides',    'description' => 'Biocontrol nematicide — 20L bulk drum.',                                    'cost_price' => 1180.00, 'sell_price' => 1562.00, 'quantity' => 12,  'base_unit' => 'drum',    'low_stock_alert' => 2],
            ['name' => 'Bacillus firmus WP 25kg',       'category' => 'Nematicides',    'description' => 'Biological nematicide — 25kg bulk sack.',                                   'cost_price' => 1250.00, 'sell_price' => 1655.00, 'quantity' => 10,  'base_unit' => 'sack',    'low_stock_alert' => 2],

            // ── Rodenticides (5) ─────────────────────────────────────────────
            ['name' => 'Bromadiolone 0.005% Bait 25kg', 'category' => 'Rodenticides',   'description' => 'Anticoagulant rodenticide bait blocks — 25kg carton.',                      'cost_price' => 380.00,  'sell_price' => 503.00,  'quantity' => 30,  'base_unit' => 'carton',  'low_stock_alert' => 5],
            ['name' => 'Brodifacoum 0.005% Bait 25kg',  'category' => 'Rodenticides',   'description' => 'Single-feed anticoagulant — 25kg carton.',                                  'cost_price' => 420.00,  'sell_price' => 556.00,  'quantity' => 25,  'base_unit' => 'carton',  'low_stock_alert' => 4],
            ['name' => 'Zinc Phosphide 80% WP 25kg',    'category' => 'Rodenticides',   'description' => 'Acute toxicant for field rodents — 25kg drum.',                             'cost_price' => 560.00,  'sell_price' => 741.00,  'quantity' => 20,  'base_unit' => 'drum',    'low_stock_alert' => 3],
            ['name' => 'Difethialone 0.0025% 25kg',     'category' => 'Rodenticides',   'description' => 'Second-generation anticoagulant pellets — 25kg.',                           'cost_price' => 480.00,  'sell_price' => 635.00,  'quantity' => 22,  'base_unit' => 'carton',  'low_stock_alert' => 3],
            ['name' => 'Flocoumafen 0.005% Bait 25kg',  'category' => 'Rodenticides',   'description' => 'Anticoagulant for resistant rat populations — 25kg.',                       'cost_price' => 500.00,  'sell_price' => 662.00,  'quantity' => 18,  'base_unit' => 'carton',  'low_stock_alert' => 3],

            // ── Adjuvants (10) ────────────────────────────────────────────────
            ['name' => 'Non-Ionic Surfactant 200L',     'category' => 'Adjuvants',      'description' => 'Spreader-sticker for pesticide coverage — 200L IBC.',                       'cost_price' => 2600.00, 'sell_price' => 3441.00, 'quantity' => 8,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Organosilicone Spreader 200L',  'category' => 'Adjuvants',      'description' => 'Supraspreader for foliar penetration — 200L IBC.',                          'cost_price' => 3800.00, 'sell_price' => 5029.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Methylated Seed Oil 200L',      'category' => 'Adjuvants',      'description' => 'Crop oil concentrate for herbicide mixes — 200L IBC.',                       'cost_price' => 3000.00, 'sell_price' => 3970.00, 'quantity' => 6,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'pH Buffer Acidifier 200L',      'category' => 'Adjuvants',      'description' => 'Lowers spray water pH — 200L IBC.',                                         'cost_price' => 2000.00, 'sell_price' => 2647.00, 'quantity' => 8,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Drift Retardant 200L',          'category' => 'Adjuvants',      'description' => 'Reduces spray drift — 200L IBC.',                                           'cost_price' => 3200.00, 'sell_price' => 4233.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Glyphosate Activator 200L',     'category' => 'Adjuvants',      'description' => 'Enhances glyphosate leaf absorption — 200L IBC.',                           'cost_price' => 2800.00, 'sell_price' => 3706.00, 'quantity' => 6,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Anti-Foam Agent 20L',           'category' => 'Adjuvants',      'description' => 'Prevents foam in spray tanks — 20L drum.',                                  'cost_price' => 180.00,  'sell_price' => 238.00,  'quantity' => 60,  'base_unit' => 'drum',    'low_stock_alert' => 8],
            ['name' => 'Compatibility Agent 200L',      'category' => 'Adjuvants',      'description' => 'Prevents incompatibility in tank mixes — 200L IBC.',                        'cost_price' => 2400.00, 'sell_price' => 3176.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Penetrant Plus 200L',           'category' => 'Adjuvants',      'description' => 'Systemic uptake enhancer for pesticides — 200L IBC.',                       'cost_price' => 3000.00, 'sell_price' => 3970.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Humectant Spreader 200L',       'category' => 'Adjuvants',      'description' => 'Slows drying to maximise contact time — 200L IBC.',                         'cost_price' => 2600.00, 'sell_price' => 3441.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],

            // ── Soil Amendments (10) ──────────────────────────────────────────
            ['name' => 'Agricultural Lime 1000kg',      'category' => 'Soil Amendments','description' => 'Raises soil pH — bulk 1-tonne bag.',                                        'cost_price' => 800.00,  'sell_price' => 1059.00, 'quantity' => 50,  'base_unit' => 'tonne',   'low_stock_alert' => 8],
            ['name' => 'Dolomite Lime 1000kg',          'category' => 'Soil Amendments','description' => 'Ca-Mg limestone for pH correction — 1-tonne bag.',                          'cost_price' => 900.00,  'sell_price' => 1191.00, 'quantity' => 40,  'base_unit' => 'tonne',   'low_stock_alert' => 6],
            ['name' => 'Gypsum 1000kg',                 'category' => 'Soil Amendments','description' => 'Soil conditioner for dispersive soils — 1-tonne bag.',                      'cost_price' => 850.00,  'sell_price' => 1125.00, 'quantity' => 35,  'base_unit' => 'tonne',   'low_stock_alert' => 5],
            ['name' => 'Biochar Fine 500kg',            'category' => 'Soil Amendments','description' => 'Activated biochar for carbon and water retention — 500kg.',                  'cost_price' => 1600.00, 'sell_price' => 2118.00, 'quantity' => 15,  'base_unit' => 'big-bag', 'low_stock_alert' => 2],
            ['name' => 'Vermicompost 1000kg',           'category' => 'Soil Amendments','description' => 'Worm castings — bulk 1-tonne bag.',                                         'cost_price' => 1200.00, 'sell_price' => 1588.00, 'quantity' => 20,  'base_unit' => 'tonne',   'low_stock_alert' => 3],
            ['name' => 'Mycorrhiza WP 25kg',            'category' => 'Soil Amendments','description' => 'Arbuscular mycorrhizal fungi — bulk 25kg sack.',                             'cost_price' => 1300.00, 'sell_price' => 1720.00, 'quantity' => 12,  'base_unit' => 'sack',    'low_stock_alert' => 2],
            ['name' => 'Rhizobium Inoculant 25kg',      'category' => 'Soil Amendments','description' => 'N-fixing bacteria for legumes — 25kg sack.',                                 'cost_price' => 480.00,  'sell_price' => 635.00,  'quantity' => 25,  'base_unit' => 'sack',    'low_stock_alert' => 4],
            ['name' => 'Potassium Silicate 200L',       'category' => 'Soil Amendments','description' => 'Liquid silicon for soil pH and plant resistance — 200L IBC.',                'cost_price' => 4800.00, 'sell_price' => 6353.00, 'quantity' => 5,   'base_unit' => 'IBC',     'low_stock_alert' => 1],
            ['name' => 'Bentonite Clay 1000kg',         'category' => 'Soil Amendments','description' => 'Water retention in sandy soils — 1-tonne bag.',                              'cost_price' => 700.00,  'sell_price' => 926.00,  'quantity' => 22,  'base_unit' => 'tonne',   'low_stock_alert' => 3],
            ['name' => 'Sulphur 90% WG 1000kg',        'category' => 'Soil Amendments','description' => 'Acidifies soil pH and supplies sulphur — 1-tonne bag.',                      'cost_price' => 1200.00, 'sell_price' => 1588.00, 'quantity' => 14,  'base_unit' => 'tonne',   'low_stock_alert' => 2],
        ];

        $rows = array_map(fn($p) => array_merge($p, [
            'created_at' => $now,
            'updated_at' => $now,
        ]), $products);

        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('wholesale_products')->insertOrIgnore($chunk);
        }
    }
}
